package ws

// All the events available on the WS API
const (
	ROOM_CREATE = "ROOM_CREATE"
	ROOM_UPDATE = "ROOM_UPDATE"
	ROOM_DELETE = "ROOM_DELETE"

	MESSAGE_CREATE = "MESSAGE_CREATE"
	MESSAGE_UPDATE = "MESSAGE_UPDATE"
	MESSAGE_DELETE = "MESSAGE_DELETE"

	USER_UPDATE         = "USER_UPDATE"
	USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"
	USER_CONNECT        = "USER_CONNECT"
	USER_DISCONNECT     = "USER_DISCONNECT"
)
